[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Hueseyin Yildiz <huess@juicyarts.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
coverage = []